apiVersion: v1
kind: ResourceQuota
metadata: 
  name: minimal
  namespace: cluster-test
spec:
  hard:
    pods: "200"
    requests.cpu: 8
    requests.memory: 30G
    requests.nvidia.com/gpu: 2 
    limits.cpu: 12
    limits.memory: 50G
    limits.nvidia.com/gpu: 2 
      #    limits:
      #      cpu: 9
      #      memory: 9G
      #      nvidia.com/gpu: 1 
      #
