apiVersion: v1
kind: LimitRange
metadata:
  name: test
  namespace: cluster-test
spec:
  limits:
  - default:
      memory: 16G
      cpu: 8
      nvidia.com/gpu: 1
    defaultRequest:
      memory: 12G
      cpu: 4
      nvidia.com/gpu: 1
    type: Container
