apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-1
  namespace: cluster-test
  labels:
    type: gpu
spec:
  template:
    spec:
      restartPolicy: Never
        #nodeSelector:
        #  name: worker02
      containers:
        - name: mnist-test
          image: registry.mohsenkamini.ir:5000/test/mnist-test:0.0.0
          resources:
            requests:
              cpu: "1"
              memory: "1G"
              nvidia.com/gpu: 1
            limits:
              cpu: "2"
              memory: "2G"
              nvidia.com/gpu: 1
