apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-agent:dcai-gitlab-agent-gitlab-kube-agent
  namespace: gitlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-kube-agent
subjects:
- kind: ServiceAccount
  name: dcai-gitlab-agent
  namespace: gitlab-agent-dcai
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-agent:dcai-admin-gitlab-agent-gitlab-kube-agent-admin
  namespace: gitlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-kube-agent-admin
subjects:
- kind: ServiceAccount
  name: dcai-admin-gitlab-agent
  namespace: gitlab-agent-dcai-admin
