apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-kube-agent
  namespace: gitlab
rules:
  - apiGroups:
    # core
     - ""
    resources:
      - "pods"
      - "pods/log"
    verbs:
      - "patch"
      - "list"
      - "get"
      - "create"
      - "delete"
      - "update"
      - "watch"
  - apiGroups:
     - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "patch"
      - "create"
      - "update"
  - apiGroups:
    # core
     - "batch"
    resources:
      - "jobs"
    verbs:
      - "patch"
      - "list"
      - "get"
      - "create"
      - "delete"
      - "update"
      - "watch"
