apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-kube-agent
  namespace: gitlab
rules:
  - apiGroups:
    # core
     - ""
    resources:
      - "pods"
      - "pods/log"
      - "pods/exec"
      - "events"
    verbs:
      - "get"
      - "create"
      - "list"
  - apiGroups:
    # core
     - "batch"
    resources:
      - "jobs"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "update"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-kube-agent-admin
  # i think this is used for gitlab admin tasks. the one who gives permission, should already have those permissions.
rules:
  - apiGroups:
    # core
     - ""
    resources:
      - "namespaces"
      - "secrets"
      - "limitranges"
      - "resourcequotas"
    verbs:
      - "create"
      - "update"
      - "patch"
        # - "list"
      - "get"
        # - "watch"
  - apiGroups:
    # core
     - "rbac.authorization.k8s.io"
    resources:
      - "roles"
      - "rolebindings"
    verbs:
      - "create"
      - "update"
      - "patch"
        # - "list"
      - "get"
        # - "watch"
  - apiGroups:
    # core
     - ""
    resources:
      - "pods"
      - "pods/log"
      - "pods/exec"
      - "events"
    verbs:
      - "create"
      - "get"
      - "list"
  - apiGroups:
    # core
     - "batch"
    resources:
      - "jobs"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "update"
      - "watch"
