apiVersion: v1
kind: ResourceQuota
metadata: 
  name: minimal
  namespace: cluster-test
spec:
  hard:
    pods: "100"
    requests.cpu: 4
    requests.memory: 9G
    requests.nvidia.com/gpu: 1 
    limits.cpu: 9
    limits.memory: 16G
    limits.nvidia.com/gpu: 1 
      #    limits:
      #      cpu: 9
      #      memory: 9G
      #      nvidia.com/gpu: 1 
      #
