apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subAdmin
rules:
  - apiGroups:
    # core
     - ""
    resources:
      - "nodes"
    verbs:
      - "list"
      - "get"
      - "watch"
  - apiGroups:
    # core
     - ""
    resources:
      - "namespaces"
      - "resourcequotas"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "create"
      - "update"
