apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subAdmin
rules:
  - apiGroups:
    # core
     - ""
    resources:
      - "nodes"
    verbs:
      - "list"
      - "get"
      - "watch"
  - apiGroups:
    # core
     - ""
     - "apiextensions.k8s.io"
    resources:
      - "namespaces"
      - "resourcequotas"
      - "customresourcedefinitions"
    verbs:
      - "list"
      - "get"
      - "watch"
      - "create"
      - "update"
      
