apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: subAdmin
  namespace: monitoring
rules:
  - apiGroups:
    # core
     - ""
    resources:
      - "pods"
      - "pods/log"
      - "pods/portforward"
      - "services"
      - "resourcequotas"
      - "secrets"
      - "configmaps"
      - "events"
      - "secrets"
    verbs:
      - "list"
      - "get"
      - "create"
      - "delete"
      - "update"
      - "watch"
  - apiGroups:
     - "apps"
    resources:
      - "daemonsets"
      - "deployments"
      - "replicasets "
    verbs:
      - "list"
      - "get"
      - "create"
      - "delete"
      - "update"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: subAdmin-system
  namespace: kube-system
rules:
  - apiGroups:
    # core
     - ""
    resources:
      - "pods"
      - "services"
      - "resourcequotas"
      - "secrets"
      - "configmaps"
      - "events"
      - "secrets"
    verbs:
      - "list"
      - "get"
      - "watch"
  - apiGroups:
     - "apps"
    resources:
      - "daemonsets"
      - "deployments"
      - "replicasets "
    verbs:
      - "list"
      - "get"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: subAdmin-gpu-operator
  namespace: gpu-operator
rules:
  - apiGroups:
    # core
     - ""
    resources:
      - "pods"
      - "pods/log"
      - "services"
      - "resourcequotas"
      - "secrets"
      - "configmaps"
      - "events"
      - "secrets"
    verbs:
      - "list"
      - "get"
      - "watch"
  - apiGroups:
     - "apps"
    resources:
      - "daemonsets"
      - "deployments"
      - "replicasets "
    resourceNames: 
      - nvidia-dcgm-exporter
    verbs:
      - "list"
      - "get"
      - "watch"
